In [1]:
import numpy as np


In [ ]:
x=np.random.randint(0,101,(3,3))
y=np.random.randint(0,101,(3,3))
print

In [2]:
# numpy slicing (in 2d array)

In [3]:
# 10x5 matrix
a=np.random.randint(10,100,(10,5))
a

array([[27, 44, 99, 53, 79],
       [39, 59, 24, 79, 16],
       [65, 21, 55, 72, 35],
       [92, 92, 77, 17, 15],
       [85, 20, 46, 13, 88],
       [62, 16, 16, 99, 24],
       [66, 88, 85, 40, 17],
       [64, 49, 11, 83, 22],
       [35, 30, 22, 86, 49],
       [21, 98, 58, 86, 41]])

In [4]:
#top5 rows
print(a[:5])

print(a[-3:])

[[27 44 99 53 79]
 [39 59 24 79 16]
 [65 21 55 72 35]
 [92 92 77 17 15]
 [85 20 46 13 88]]
[[64 49 11 83 22]
 [35 30 22 86 49]
 [21 98 58 86 41]]


In [5]:
# 1column
print(a[:,1])

#first 3 column
print(a[:,:3])

#last 3 column
print(a[:,-3:])

#0,2,4 column
print(a[:,[0,2,4]])

# 1st 5 rows and 1st 3column
print(a[:5,:3])

[44 59 21 92 20 16 88 49 30 98]
[[27 44 99]
 [39 59 24]
 [65 21 55]
 [92 92 77]
 [85 20 46]
 [62 16 16]
 [66 88 85]
 [64 49 11]
 [35 30 22]
 [21 98 58]]
[[99 53 79]
 [24 79 16]
 [55 72 35]
 [77 17 15]
 [46 13 88]
 [16 99 24]
 [85 40 17]
 [11 83 22]
 [22 86 49]
 [58 86 41]]
[[27 99 79]
 [39 24 16]
 [65 55 35]
 [92 77 15]
 [85 46 88]
 [62 16 24]
 [66 85 17]
 [64 11 22]
 [35 22 49]
 [21 58 41]]
[[27 44 99]
 [39 59 24]
 [65 21 55]
 [92 92 77]
 [85 20 46]]
